### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/wekan_ynh#26]
I have install wekan today and got this:
```
root@demo:/home/admin# /opt/node_n/bin/node /var/www/wekan/main.js
/var/www/wekan/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at packages/idmontie_migrations.js:38:15
    at packages/idmontie_migrations.js:255:4
    at packages/idmontie_migrations.js:267:3
    at infos.forEach.info (/var/www/wekan/programs/server/boot.js:414:13)
    at Array.forEach (<anonymous>)
    at /var/www/wekan/programs/server/boot.js:413:9
    at /var/www/wekan/programs/server/boot.js:463:5
```

**Comment by zamentur** [comment]
It seems it's not the true error but I got a blank page. I am searching...

**Comment by zamentur** [comment]
Ok so the issue is this app doesn't setup correctly on a root domain !

I need to change
```
Environment=ROOT_URL=https://my.sub.domain.com// PORT=8081
```
By
```
Environment=ROOT_URL=https://my.sub.domain.com/ PORT=8081
```

**Comment by anmol26s** [comment]
Where did you changed this line?

**Comment by yalh76** [comment]
> 
> 
> Where did you changed this line?

this line are in the systemd file

**Comment by yalh76** [comment]
Can we close that issue ?

**Comment by alexAubin** [comment]
If you say we can, yup :D
