### ISSUE TITLE
Reset your password -   Internal server error

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/wekan_ynh#43]
```
Jul  9 12:36:18 y postfix/submission/smtpd[2735]: connect from localhost[127.0.0.1]
Jul  9 12:36:18 y postfix/submission/smtpd[2735]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.2 with cipher DHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jul  9 12:36:18 y postfix/submission/smtpd[2735]: lost connection after STARTTLS from localhost[127.0.0.1]
Jul  9 12:36:18 y postfix/submission/smtpd[2735]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=1 commands=2
Jul  9 12:36:18 y wekan[726]: Exception while invoking method 'forgotPassword' { stack: 'Error: unable to verify the first certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:643:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)',
Jul  9 12:36:18 y wekan[726]:   source: 'method' }
```

**Comment by arthurlogilab** [comment]
The certificate which is used by postfix is a letsencrypt certificate

**Comment by yalh76** [comment]
Can you try disabling TLS support ?
There is no need to have TLS activated as wekan and the smtp server are the same....

**Comment by arthurlogilab** [comment]
I'm not sure I follow

**Comment by yalh76** [comment]
Without news, I close that issue. Feel free to reopen that issue
