### ISSUE TITLE
Backup failed, the upgrade process was aborted.

### ISSUE THREAD

**Issue by R-0ne** [YunoHost-Apps/wekan_ynh#47]
the log file

```
2019-07-27 05:52:43,200: WARNING - 1478 [34m[1m[DEBUG][0m: DEBUG   - ++ sed -r 's/"/\"\"/g'
2019-07-27 05:52:43,200: DEBUG - 1478 + ynh_die
2019-07-27 05:52:43,200: WARNING - 1478 [34m[1m[DEBUG][0m: DEBUG   - + local dest=apps/wekan/backup/etc/nginx/conf.d/kaban.r-one.info.d/wekan.conf
2019-07-27 05:52:43,201: DEBUG - 1478 + local legacy_args=mc
2019-07-27 05:52:43,201: WARNING - 1478 [34m[1m[DEBUG][0m: DEBUG   - + echo '"/etc/nginx/conf.d/kaban.r-one.info.d/wekan.conf","apps/wekan/backup/etc/nginx/conf.d/kaban.r-one.info.d/wekan.conf"'
2019-07-27 05:52:43,201: DEBUG - 1478 + args_array=([m]=message= [c]=ret_code=)
2019-07-27 05:52:43,201: WARNING - 1479 [34m[1m[DEBUG][0m: DEBUG   - ++ dirname /home/yunohost.backup/tmp/wekan-pre-upgrade1/apps/wekan/backup/etc/nginx/conf.d/kaban.r-one.info.d/wekan.conf
2019-07-27 05:52:43,202: DEBUG - 1478 + declare -Ar args_array
2019-07-27 05:52:43,202: WARNING - 1479 [34m[1m[DEBUG][0m: DEBUG   - + mkdir -p /home/yunohost.backup/tmp/wekan-pre-upgrade1/apps/wekan/backup/etc/nginx/conf.d/kaban.r-one.info.d
2019-07-27 05:52:43,202: DEBUG - 1479 + local message
2019-07-27 05:52:43,202: WARNING - 1479 [34m[1m[DEBUG][0m: DEBUG   - + ynh_print_info 'Backing up the MongoDB database...'
2019-07-27 05:52:43,202: DEBUG - 1479 + local ret_code
2019-07-27 05:52:43,203: WARNING - 1479 [34m[1m[DEBUG][0m: DEBUG   - + local legacy_args=m
2019-07-27 05:52:43,203: DEBUG - 1479 + ynh_handle_getopts_args
2019-07-27 05:52:43,203: WARNING - 1480 [34m[1m[DEBUG][0m: DEBUG   -=message=)
2019-07-27 05:52:43,203: DEBUG - 1480 + set +x
2019-07-27 05:52:43,204: WARNING - 1480 [34m[1m[DEBUG][0m: DEBUG   - + declare -Ar args_array
2019-07-27 05:52:43,204: DEBUG - 1480 + echo ''
2019-07-27 05:52:43,204: WARNING - 1480 [34m[1m[DEBUG][0m: DEBUG   - + local message
2019-07-27 05:52:43,204: DEBUG - 1480 + exit 1
2019-07-27 05:52:43,204: WARNING - 1480 [34m[1m[DEBUG][0m: DEBUG   - + ynh_handle_getopts_args 'Backing up the MongoDB database...'
2019-07-27 05:52:43,205: WARNING - 1480 [34m[1m[DEBUG][0m: DEBUG   - + set +x
2019-07-27 05:52:43,205: WARNING - 1481 [34m[1m[DEBUG][0m: DEBUG   - + echo '! Helper used in legacy mode !'
2019-07-27 05:52:43,205: WARNING - 1481 [34m[1m[DEBUG][0m: DEBUG   - + set +x
2019-07-27 05:52:43,206: WARNING - 1481 [34m[1m[DEBUG][0m: DEBUG   - + echo 'Backing up the MongoDB database...'
2019-07-27 05:52:43,206: WARNING - 1481 [34m[1m[DEBUG][0m: DEBUG   - + mongodump --db wekan -o ./dump
2019-07-27 05:52:43,206: WARNING - 1481 [34m[1m[DEBUG][0m: DEBUG   - + ynh_exit_properly
2019-07-27 05:52:43,206: WARNING - 1481
2019-07-27 05:52:43,407: DEBUG - 1618 action [3128.1] executed in 1.390s
2019-07-27 05:52:43,408: WARNING - 1587 Impossible de sauvegarder l’application 'wekan'
2019-07-27 05:52:43,408: DEBUG - + '[' 1 -eq 0 ']'
2019-07-27 05:52:43,408: WARNING - Traceback (most recent call last):
2019-07-27 05:52:43,408: DEBUG - + ynh_die '--message=Backup failed, the upgrade process was aborted.'
2019-07-27 05:52:43,409: WARNING -   File "/usr/lib/moulinette/yunohost/backup.py", line 701, in _collect_app_files
2019-07-27 05:52:43,409: DEBUG - + local legacy_args=mc
2019-07-27 05:52:43,409: WARNING -     raise_on_error=True, chdir=tmp_app_bkp_dir, env=env_dict)[0]
2019-07-27 05:52:43,409: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2019-07-27 05:52:43,409: WARNING -   File "/usr/lib/moulinette/yunohost/hook.py", line 397, in hook_exec
2019-07-27 05:52:43,410: DEBUG - + declare -Ar args_array
2019-07-27 05:52:43,410: WARNING -     raise YunohostError('hook_exec_failed', path=path)
2019-07-27 05:52:43,410: DEBUG - + local message
2019-07-27 05:52:43,410: WARNING - YunohostError: Échec de l’exécution du script : /tmp/backup_VLT1Xm
2019-07-27 05:52:43,411: DEBUG - + local ret_code
2019-07-27 05:52:43,411: WARNING - 1619 Il n’y a rien à sauvegarder
2019-07-27 05:52:43,411: DEBUG - + ynh_handle_getopts_args '--message=Backup failed, the upgrade process was aborted.'
2019-07-27 05:52:43,411: WARNING - Backup failed, the upgrade process was aborted.
2019-07-27 05:52:43,412: DEBUG - + set +x
2019-07-27 05:52:43,412: DEBUG - + echo 'Backup failed, the upgrade process was aborted.'
2019-07-27 05:52:43,412: DEBUG - + exit 1
2019-07-27 05:52:43,553: ERROR - Impossible de mettre à jour wekan
```

**Comment by yalh76** [comment]
can you try to upgrade to the last version using `yunohost app upgrade wekan` and provide the link to the full log if it's not working

**Comment by yalh76** [comment]
Since there is no news since 2 months, I close that issue. Feel free to reopen it if needed.
